const language = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log(language);
const firstElement = language[0];
console.log('the first element of the array is', firstElement);
const thirdElement = language[2];
console.log('the 3rd element of the array is', thirdElement);
const length = language.length;
console.log('The length of the array is', length);
const lastElement = language[length - 1];
console.log('The last element of the array is', lastElement);
